# Data paths
data:
  raw: data/01_raw/winequality-red.csv
  interim: data/02_interim/
  processed: data/03_processed/
  external: data/04_external/

# Model parameters
model:
  random_state: 42
  test_size: 0.2
  n_estimators: 100
  max_depth: None

# Logging configuration
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  datefmt: '%Y-%m-%d %H:%M:%S'
